kentcdodds/babel-plugin-macros

other/docs/author.md, other/docs/user.md, src/__tests__/__snapshots__/index.js.snap, src/__tests__/fixtures/emotion.macro.js, src/__tests__/fixtures/eval.macro.js, src/__tests__/index.js, src/index.js
**What**: changes `macros` in the regex to `macro`
**Why**: Because you're actually only importing a single `macro`.
**How**: Mostly the regex, but also update the docs to reference a single `macro` rather than `macros`.
=> fix: macros -> macro. ref #7

__mocks__/fake/macro.js, src/__tests__/__snapshots__/index.js.snap, src/__tests__/index.js, src/index.js
closes #16
**What**: Checks for relative path if the path starts with `.`
**Why**: To fix #16 
**How**: using `indexOf` because technically we support Node v4 I guess.
=> fix: requirePath can now work with absolute/node_modules paths

README.md, other/docs/author.md, package.json, src/__tests__/index.js, src/index.js
This forwards the `babel` argument to each macro applied. This makes it easier to write a macro so you don't have to add `babel-core` to your dependencies yourself if you wouldn't otherwise need it.
=> feat: forward babel to the macro

.all-contributorsrc, README.md, __mocks__/error-thrower/macro.js, src/__tests__/__snapshots__/index.js.snap, src/__tests__/index.js, src/index.js
**What**:
Fix npm urls with macros that have slashes. e.g. `emotion/macro` Previously, the npm url would be https://www.npmjs.com/package/emotion/macro, now it will be https://www.npmjs.com/package/emotion
**Why**:
Because the pages with the slashes don't exist.
**How**:
```js
.replace(/(\/.*)/g, '')
```
=> fix: show correct npm url for macros with a slash

other/docs/author.md
**What**:
reference was spelled as renference
**Why**:
could confuse people
**How**:
Text change
=> Spelling error in README.md

.all-contributorsrc, README.md, other/docs/author.md
**What**:
Fix minor typo in author documentation.
**Why**:
Because accuracy and correctness are cool!
**How**:
Replaced `createMacros` with `createMacro` in `author.md`.
**Note**:
Some of your automated wizardry (`kcd-scripts` running `doctoc`) added a TOC to the README, let me know if you want it removed from this PR. Thanks!
=> docs: fix comment typo in macro author documentation

.all-contributorsrc, README.md, src/index.js
**What**:
Config setup (in package.json, babel-macros.config.js, etc...) was never being picked up and passed to the macros
**Why**:
The experimental option of configs won't work
**How**:
I added the property of `configName` to `macroWrapper` in the `createMacro` function. We could do this in the `getConfig` function instead and change the `macro.configName` to `macro.options.configName`
Let me know if you would prefer the configName to remain nested in the options of the macroWrapper and I can make that code change
=> Fixed issue with configName never being found in getConfig function

src/__tests__/__snapshots__/index.js.snap, src/__tests__/fixtures/emotion-esm.macro.js, src/__tests__/index.js, src/index.js
**What**:
Macros exported with `export default createMacro(...)` and compiled to commonjs are currently not supported. Trying to use one results in this error:
```
The macro imported from "./fixtures/esm-export.macro.js" must be wrapped
in "createMacro" which you can get from "babel-plugin-macros". Please refer
to the documentation to see how to do this properly:
https://github.com/kentcdodds/babel-plugin-macros/blob/master/other/docs/author.md#writing-a-macro
```
**Why**:
If the rest of the macro project is using `import` & `export`, it's a bit of a bummer to use `module.exports = createMacro(...)`.
**How**:
Use a helper similar to Babel's own `_interopRequireDefault` that checks for the `__esModule` flag on the module and returns its `default` property if it exists, else returns the …
=> feat: support compiled es modules

other/docs/macros.md
**What**:
`raw.macro` is a babel macro to read file contents at build time (similar to webpack `raw-loader`). This could be useful in environment where webpack is not available / not extensible (for example new `create-react-app` with babel-plugin-macro built-in)
**Why**:
As suggested in twitter https://twitter.com/kentcdodds/status/964860739033772032
**How**:
I created this PR via GitHub desktop UI (including commiting this change) so maybe there's something missing. I also think I don't need to add myself as contributor because this is just a minor update not affecting babel-plugin-macros itself
=> add raw.macro to the list of existing macro

.all-contributorsrc, README.md, src/index.js
As discussed in FWeinb/astexplorer#1 this will make the `require` function configurable to make it possible to customise the require logic without having to deal with webpack.
=> Make `require` configurable

.eslintcache, .gitignore, other/docs/author.md, src/__tests__/index.js, src/index.js
Useful for relative macro paths - when I want to convert a macro import to sibling, regular, file.
=> feat(source param): Call macro with additional source parameter

other/docs/author.md, package.json, src/__tests__/__snapshots__/index.js.snap, src/__tests__/fixtures/keep-imports.macro.js, src/__tests__/index.js, src/index.js
Closes #74, review welcome :)
Btw I'm still getting errors when running tests locally. After I fork and clone repo, run `npm run setup -s` I see a lot of failed tests. Most of them with following error:
```
● macros › does nothing to code that does not import macro
TypeError: Cannot read property 'mockClear' of undefined
23 | afterEach(() => {
24 |   // eslint-disable-next-line
> 25 |   require('babel-plugin-macros-test-fake/macro').innerFn.mockClear()
26 | })
27 |
28 | expect.addSnapshotSerializer({
```
Also few failed snapshots:
```
● macros › when a plugin that replaces paths is used, macros still work properly
expect(value).toMatchSnapshot()
Received value does not match stored snapshot 1.
- Snapshot
+ Received
@@ -4,7 +4,7 @@
global.result = result
↓ ↓ ↓ ↓ ↓ ↓
- const result = …
```
=> Allow macros to keep imports

other/mock-modules/babel-plugin-path-replace/index.js, package.json, src/__tests__/__snapshots__/index.js.snap, src/__tests__/fixtures/eval.macro.js, src/__tests__/index.js, src/index.js
**What**:
When macro is configured to keep imports, the import line is processed twice? which causes error `Cannot read property 'referencePaths' of undefined`.
Here's the repo to reproduce the bug: https://github.com/tricoder42/lingui-issue-328
**Why**:
`path.scope.getBinding(localName)` returns undefined for `localName === '_macro'`, which is the import of macro.
https://github.com/kentcdodds/babel-plugin-macros/blob/d319f1066a41b412f20eadbcd5230ce178614925/src/index.js#L140
**How**:
I've just added a guard that `referencePaths` isn't accessed on undefined.
=> Skip invalid imports

README.md
**What**:
Note that Create React App does not suffer from a common problem using Macros.
**Why**:
https://github.com/facebook/create-react-app/issues/2730#issuecomment-426550137
We don't want users thinking they have to purge the cache, as this will be very detrimental to their rebuild speed.
It's also important because these configuration values are out of their reach; ejecting to "fix" this would be unnecessary.
=> Add CRA note to caveats

src/__tests__/__snapshots__/index.js.snap, src/__tests__/fixtures/jsx-id-prefix.macro.js, src/__tests__/fixtures/jsx-id-prefix.plugin.js, src/__tests__/index.js, src/index.js
This fixes the problem described in #95 
While I know the applied technique can be called controversial, but it doesn't contradict macros usage, where macros applications aren't merged. At the moment I cannot specify where to run the macro in babel plugins chain, while it is possible to do with plugins.
Here, for example, just printing plugin (pprint.macro.js):
```javascript
module.exports = require('babel-plugin-macros').createMacro(function({state}) {
console.log(require("@babel/generator").default(state.file.scope.path.node).code)
})
```
I run it with:
```
$ npx babel --plugins babel-plugin-macros --presets @babel/preset-env input.js
```
And inside the input.js just a simple async generator function:
```javascript
import "./pprint.macro"
async function* fn1() {
yield await hi
}
``` …
=> Order of application in non-macro transforms chain

src/index.js
**What**: This defaults the filename variable to an empty string
**Why**: ASTexplorer.net is not working for babel-plugin-macros because we need the filename and it's not being provided in that environment. I'd considered just making the fix there, but I suspect there are other situations where this could be helpful.
**How**: Using destructuring defaults
=> fix: add default empty filename

src/index.js
**What**:
Allows the plugin to accept a custom path resolve function.
**Why**:
ASTExplorer doesn't have access to the `fs` module, so it throws an error when attempting to use `resolve.sync`.
**How**:
A `resolvePath` option is added to `macrosPlugin`, which is a function that receives the `source` path string and the `basedir` directory string. If `resolvePath` is not provided, `resolve.sync` will be used.
**Notes:**
I didn't see any tests for the existing `require` option for `macrosPlugin`, so it wasn't immediately obvious how I should test this. While not a substitute for a proper test, I did link it to a local clone of ASTExplorer and it worked as expected.
Fixes #102
=> Allow custom path resolve function

other/docs/author.md, src/__tests__/__snapshots__/index.js.snap, src/__tests__/fixtures/config/babel-plugin-macros.config.js, src/__tests__/fixtures/primitive-config/babel-plugin-macros.config.js, src/__tests__/fixtures/primitive-config/code.js, src/__tests__/fixtures/primitive-config/configurable.macro.js, src/__tests__/index.js, src/index.js
Fixes #112 
I'm missing test coverage, but I'm also not familiar with the way this test environment is set up. Some tips on how to test this well would be appreciated.
=> Allow macro config to come from plugin options in babel config.

src/__tests__/__snapshots__/index.js.snap, src/__tests__/fixtures/eval-macro.js, src/__tests__/index.js, src/index.js
**What**: Resolving #131 by adding a new option called `isMacrosName` for the plugin.
**Why**: Allows the user to selectively accept modules as a macro for this plugin.
**How**: This option will optionally overwrite the original behaviour, so backwards compatibility is kept.
=> Add isMacrosName option

src/__tests__/__snapshots__/index.js.snap, src/index.js
The goal of this PR is to only log the following error messages when they need to be logged:
They happen when no config is specified (either in babel or via cosmoconfig). Most babel macros work perfectly well without config so this message is incorrect and the macro itself should throw if the config is missing.
Moreover, the error message states: `Please see the error thrown for more information.` but no error is thrown. I've written in this PR what I believe is the expected behavior.
Related:
- https://github.com/facebook/create-react-app/issues/7524
- https://github.com/styled-components/styled-components/issues/2713
=> fix: Do not log error message when config is missing

src/index.js
**What**: https://github.com/kentcdodds/babel-plugin-macros/issues/87
**Why**: In case you have `babel-plugin-macros` loaded outside of `process.cwd()` it cannot resolve modules realtively to itself.
**How**: Added the node_modules folder including `babel-plugin-macros` as a fallback path.
=> feat(resolve): add fallback path to be able to resolve modules relatively to `babel-plugin-macros`

src/index.js
**What** / **Why** / **How**:
Well, it's a typo.
=> fix: getConfigExporer typo

package.json, src/index.js
Resolves: https://github.com/kentcdodds/babel-plugin-macros/issues/121
This uses [`@babel/traverse`](https://babeljs.io/docs/en/babel-traverse) rather than the stateful one
=> use babel traverse

other/docs/author.md, src/index.js
When a macro is defined in a package with `"type": "module"` set in `package.json`, `babel-plugin-macros` uses `require` to load it. This fails because require is not allowed on an es module (which the macro is now assumed to be). The answer for the moment is for the macro not to be a module, which requires that its extension be `macro.cjs` and that it be imported with an explicit extension. This change ensures that that is possible.
=> Allow macros to end in .cjs

README.md
twin.macro is fairly actively developed and their caching issue links to some possible solutions in babel.
**What**:
update README reference to another caching issue
**Why**:
Following other solutions could help find workarounds to caching issues.
**How**:
Update to the README
**Checklist**:
=> update README reference to another caching issue

src/index.js
**What**:
Babel macros that are written in typescript and not transpiled prior to being run through `babel-plugin-macros` are currently not detected because `resolve` defaults to only looking for the `".js"` extension.
=> support more extensions that babel macros can be written in
