README.md

**What**:
Adds explanation of why this project exists to the README
**Why**:
To help users understand what this is; see #4.
**How**:
By editing the README (on GitHub :wink:)
@kentcdodds could you add me to the contributors list in the readme for the project? (Too lazy to clone the repo and run the p-s script right now :see_no_evil:)

docs: Explain why this project exists

---

README.md
src/__tests__/fixtures/eval.macros.js

**What**: Add usage docs
**Why**: Because the API is more solid. Now people need to know how to use this.
**How**: Updated the README.md. Also made a slight change to one of the tests.

docs: add usage documentation

---

README.md

**What**: docs
**Why**: Clarify use case of this library
Closes #9

docs: Add FAQ section

---

README.md

Just a typo. Thank you for the other corrections and proofreading! 👍

docs: Fix missing operator

---

README.md

**What**: Improve example in FAQ
**Why**: People find the trivial example too confusing (doesn't explain reasoning behind this lib)

docs: Improve example in FAQ

---

.all-contributorsrc
README.md
__mocks__/error-thrower.macro.js
error.js
other/docs/author.md
package.json
src/__tests__/__snapshots__/index.js.snap
src/__tests__/fixtures/error-thrower.macro.js
src/__tests__/fixtures/macro-error-thrower.macro.js
src/__tests__/index.js
src/index.js

**What**: adds `MacroError`
**Why**: to encourage user-friendly error messages (closes #22)
**How**: Magic. Also updated `babel-plugin-tester` which kinda messed up snapshots a bit. Sorry.

feat(MacroError): add MacroError

---

README.md

**What**: Add link to the Kent's Babel.js guest blog post on the babel blog.
**Why**: To increase understanding of the problem motivation and solutions for babel-macros
**How**:

Add link to the Kent's Babel.js guest blog post on the babel blog.

---

other/docs/author.md

1. remove unused import
2. fix macro import
**What**:
Updates in the author documentation
**Why**:
imports were wrong
**How**:
remove `path` import and `create` -> `createMacro`

docs: Update author.md

---

README.md

**What**:
**Why**:
for issue https://github.com/kentcdodds/babel-plugin-preval/issues/19
**How**:

docs(README): add babel cache caveats

---

README.md
other/docs/macros.md

**What**: Document what type of dependency that macros should be.
**Why**: Because it's not documented.
**How**: I edited `README.md` and `macros.md`.
Please let me know if I should put anything else.

docs: clarify dependency type

---

.all-contributorsrc
README.md
other/docs/user.md

**What**: Added documentation for usage with create-react-app
**Why**: To make it easier for folks to get started when using create-react-app and also let them know of considerations they should make when deciding to use this with cra.
**How**: Updated user.md

Added create-react-app usage to user.md

---

other/docs/macros.md

**What**:
Add a macro implementation to the macros list.
**Why**:
`penv.macro` can handle environment variable picking more convenient, [more details](https://github.com/chengjianhua/penv.macro).
I hope more people could use this to solve the pain point of configuring the variable or logics branch for the specified environment in one place. 
**How**:

docs(macros): added `penv.macro` to the macros list

---

other/docs/macros.md

**What**: Added `lqip.macro` to the list of macros. Do not merge it yet - I haven't tested it properly.
**Why**:
**How**:

Add lqip.macro

---

other/docs/macros.md

**What**:
Add [`css-to-rn.macro`](https://github.com/jhen0409/css-to-rn.macro) to the macros list.
It's saved CSS parse and `css-to-react-native` transform at build time.
**Why**:
**How**:

docs: add css-to-rn.macro

---

other/docs/macros.md

Not sure what more to describe here 😁

docs: add idx.macro

---

other/docs/user.md

**What**: Docs improvement
**Why**: Users need to know how to config their macro
**How**:

add config (EXPERIMENTAL!) to user guide

---

README.md

**What**:
**Why**: Makes it easier to contribute. Different forks/branches can work
**How**:

use relative links

---

.travis.yml

**What**: CI
**Why**: We should test against the last LTS branch, which is now 10.
**How**: Change from `8` to `10`.

ci: test on Node.js 10

---

other/docs/user.md

**What**: docs
**Why**: outdated
**How**: updated docs

macros in CRA are live, update docs

---

.travis.yml
other/babel-config.js

**What**:
Ensure the test suite works on Windows
**Why**:
To fix #115 
**How**:
1. Reproduce failures in Windows CI environment.
2. Fix failures

WIP: Add CI run in Windows environment

---

.travis.yml

**What**:
Another attempt on #118
Also made sure both test runs complete successfully before publishing
**How**:
Read Travis docs better

chore: rearrange CI stages and disable Windows stage on main repo

---

other/docs/user.md

**What**: adding babel.config.js to user docs
**Why**: for the sake of completeness
Not sure this is needed 🤷‍♀

docs: adding babel.config.js to user docs

---

other/docs/author.md

Small correction: the package is called do-sync, not do-async
Because it's otherwise confusing?
I removed a letter
Thanks for all your hard work!

do-async -> do-sync

---

other/docs/author.md

fix: Typo in Author Docs

---

package.json
src/index.js

Fixes #164, a regression of https://github.com/kentcdodds/import-all.macro/issues/7.
We need a test for the regression so that it doesn't break again, and (assuming this is still the right fix for the original issue) also we will have to find a different fix for the issue I have reopened, #121.

Revert d5d44a6 to fix regression

---

README.md

**What**: Fixed some links in readme
**Why**: Some links are broken
**How**: Undid part of ccc43ec0
**Checklist**:

Fix some links in readme

---

src/__tests__/fixtures/eval-macro.js

**What**:
Probably the new kcd-scripts introduced new lint rule or something. Lack
of lockfile made build less reproducible.
**Why**:
**How**:
**Checklist**:

chore: fix build

---

other/mock-modules/@scope/package/macro.js
src/__tests__/__snapshots__/index.js.snap
src/__tests__/index.js

**What**:
No changes, just one more test.
**Why**:
**How**:
**Checklist**:

Add test for macro in the scoped npm package

---

CONTRIBUTING.md

Update egghead instruction link
**What**:
Update contribution instruction link
**Why**:
For better documentation & instruction for contributors ✨
**How**:
Updated link address ✏️
**Checklist**:

Fix: update link

---

other/docs/author.md

Minor change to remove redundant text from `auth.md`
**What**:
Remove redundant text from `auth.md`
**Why**:
For better documentation ✨
**How**:
Removed redundant text ✏️
**Checklist**:

Fix: remove redundant word
